import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import MainLoginAndDashBoard from "@/Components/ClientSideComponents/MainComponentForDashBoard/MainLoginAndDashBoard";
import { Toaster } from 'react-hot-toast';
import ReduxStoreProvider from "./ReduxStoreProvider";
import ReduxPersistStoreProvider from "./ReduxPersistStoreProvider";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Admin Panel",
  description: "Generated by admin panel",
  icons:{
    icon:'/user-gear.png'
  }
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased bg-white`}
      >
        <ReduxStoreProvider>
          <ReduxPersistStoreProvider>
            <Toaster
              position="top-center"
              toastOptions={{
                className: "",
                duration: 5000,
                style: {
                  background: "#363636",
                  color: "#fff",
                  zIndex: 99999999999,
                },
              }}
            />
            <MainLoginAndDashBoard>{children}</MainLoginAndDashBoard>
          </ReduxPersistStoreProvider>
        </ReduxStoreProvider>
      </body>
    </html>
  );
}
